name: adolescence_chat_bot
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:

  auto_route: ^8.1.3
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.2.1
  flutter_svg: ^2.0.10+1
  go_router: ^14.1.2
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  intl: ^0.19.0
  jiffy: ^6.3.1
  logger: ^2.3.0
  pinput: ^4.0.0
  shared_preferences: ^2.2.3
  speech_to_text: ^6.6.0
  very_good_analysis: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
